default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: ruby_bash_online_development

test:
  <<: *default
  database: ruby_bash_online_test

production:
  <<: *default
  database: ruby_bash_online_production
